services:
  - type: web
    name: humanbaze-web
    runtime: static
    buildCommand: "npm ci --legacy-peer-deps && npm run build"
    staticPublishPath: "dist"
    previews:
      generation: automatic
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
