services:
  - type: static_site
    name: humanbaze-web
    env: static
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
