services:
  - type: web
    name: humanbaze-web
    runtime: static
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"
    previews:
      generation: automatic
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
